name: Secrets Demo

on:
  workflow_dispatch:

jobs:

  secret-job:

    runs-on: ubuntu-latest

    steps:

      - name: Print Secret

        run: |
          echo "Secret Value:"
          echo "${{ secrets.MY_SECRET }}"